apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-frontend
  template:
    metadata:
      labels:
        app: agent-frontend
    spec:
      containers:
      - name: agent-frontend
        image: unfydrepo.azurecr.io/unfydrepo/agent-frontend:{{IMAGE_TAG}}
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: agent-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4200
  selector:
    app: agent-frontend
